apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq
  namespace: roboshop
data:
  RABBITMQ_DEFAULT_USER: roboshop
  RABBITMQ_DEFAULT_PASS: roboshop123

---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: rabbitmq
  namespace: roboshop

spec:
  replicas: 1
  selector:
    matchLabels:
      component: db
      project: roboshop
  
  template:
    metadata :
      labels: 
        component: db
        project: roboshop
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3
        envFrom:
        - configMapRef:
            name: rabbitmq
    

---
apiVersion: v1 
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop

spec:
  type: ClusterIP 
  selector:
    component: db
    project: roboshop
  ports:
  - protocol : TCP
    port: 5762
    targetPort: 5762
  