apiVersion: v1 
kind: ConfigMap
metadata: 
  name: user
  namespace: roboshop
data: 
  REDIS_URL: "redis://redis:6379"
  MONGO_URL: "mongodb://mongodb:27017/users"
  MONGO: "true"

---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: user
  namespace: roboshop

spec:
  replicas: 1
  selector:
    matchLabels:
      component: app
      project: roboshop
  
  template:
    metadata :
      labels: 
        component: app
        project: roboshop
    spec:
      containers:
      - name: user
        image: vasimphatan/user:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
           name: user
        

---
apiVersion: v1 
kind: Service
metadata:
  name: user
  namespace: roboshop

spec:
  type: ClusterIP 
  selector:
    component: app
    project: roboshop
  ports:
  - protocol : TCP
    port: 8080
    targetPort: 8080

